prometheus:
  prometheusSpec:
    retention: 1d
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 200Mi
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    nodePort: 30900
grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30901
  resources:
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 400Mi
  persistence:
    enabled: false
  livenessProbe:
    initialDelaySeconds: 150
    timeoutSeconds: 30
    periodSeconds: 15
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 15
    failureThreshold: 10

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 150m
      memory: 200Mi
