prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    serviceMonitorSelectorNilUsesHelmValues: false

  service:
    type: NodePort
    nodePort: 30900

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  service:
    type: NodePort
    nodePort: 30903

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30901
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
