replicaCount: 2

image:
  repository: ghcr.io/meoha-glitch/devsecops-demo-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: app.devsecops.local
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  APP_VERSION: "1.0.0"

healthCheck:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
