replicaCount: 2

image:
  repository: ghcr.io/meoha-glitch/devsecops-demo-app
  tag: "2e22d62c2f597facc3a820e3ecbf6a4fca95770a"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: dev.devsecops.local
  path: /

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

env:
  APP_VERSION: "dev"

healthCheck:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
